# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestAppDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_modular_headers!
  pod 'MattValidator', :path => '../'

  # Pods for TestAppDemo

end
