# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestAppDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_modular_headers!
   #pod 'MattValidator', :path => '../'
   pod 'MattValidator'
#pod 'MattValidator', :git => 'https://github.com/manishlodhari09/MattValidator.git', :tag => '1.0.1'
  # Pods for TestAppDemo

end
